---
title: "Design goals, technical implementation and practical use of Another data entry system (Andes)"
french_title: "Objectifs de conception, mise en œuvre technique et utilisation pratique de Another data entry system (Andes)"
year: 2024
report_number: nnn
author: |
  Daniel Ricard^1^,
  David Fishman^1^,
  Lindsay Beazley^2^,
  Brian Boivin^3^,
  Jamie Emberley^4^,
  Ryan Martin^4^,
  Nicolas Rolland^1^,
  David Sean-Fortin^3^,
  Quentin Stoyel^1^ and 
  Pablo Vergara^1^
author_list: "Ricard, D., Fishman, D., Beazley, L., Boivin, B., Emberley, J., Martin, R., Rolland, N., Sean-Fortin, D., Stoyel, Q. and Vergara, P."
region: Gulf Region
french_region: Région du Golfe
isbn: "XXX"
address: |
  ^1^Gulf Fisheries Centre, Fisheries and Oceans Canada, 343 Université Avenue, Moncton, New Brunswick, E1C 9B6\
  ^2^Bedford Institute of Oceanography, Fisheries and Oceans Canada, 1 Challenger Dr., Dartmouth, Nova Scotia, B2Y 4A2\
  ^3^Institut Maurice Lamontagne, Fisheries and Oceans Canada, 850 Rte de la Mer, Mont-Joli, Québec, QC G5H 3Z4\
  ^4^Saint Andrews Biological Station, Fisheries and Oceans Canada, 125 Marine Science Dr., St. Andrews, New Brunswick, E5B 0E4\
french_address: |
     Direction des Sciences\
     Région du Golfe\
     Pêches et Océans Canada\
     Moncton, Nouveau-Brunswick, E1C 5K4, Canada\
phone: "(555) 555-5555"
author_footnote: "Email: Daniel.Ricard@dfo-mpo.gc.ca | telephone: (506) 377-9527"
abstract: |
  An event logger and data entry system to facilitate the capture of information collected during scientific field work conducted by DFO Gulf Region was developed. The application, called "Another data entry system" (Andes) was implemented as a browser-based environment that facilitates its deployment in a variety of data capture scenarios. Here, we describe the design goals and implementation details of Andes, and present a number of usage cases. Although the system is tailored primarily for use on fishery-related ecosystem surveys, the flexibility of the application in terms of adapting to new gear types and deployment options promotes its use in a wide variety of applications. To promote transparency, longevity, endorsement and use of Andes by other scientific groups, the application utilizes Open Source software and a shared code development platform. 
french_abstract: |
  Un système d'entrée de données pour faciliter la saisie des informations recueillies lors des activités scientifiques menées par la Région du Golfe du MPO a été développé. L'application, qui s'appelle "Another data entry system" (Andes), a été mise en œuvre en tant qu'environnement basé sur un fureteur, ce qui facilite son déploiement dans une variété de scénarios de saisie de données. Les objectifs de conception et les détails de mise en œuvre d'Andes sont décrits, et un certain nombre de cas d'utilisation sont présentés. Pour promouvoir l'utilisation d'Andes par d'autres groupes scientifiques et assurer la pérennité du projet, l'application s'appuie sur des logiciels code source ouvert et utilise une plate-forme de développement de code partagé.
show_continued_text: true
output:
 csasdown::techreport_pdf:
   includes:
     in_header: "glossary.tex"
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: true
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdown::render('_bookdown.yml')
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
 - \usepackage{multirow}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
```



